// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prioritify.Data.DbContexts;

#nullable disable

namespace Prioritify.Data.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prioritify.Data.Tables.TbAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("flAccountId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flCreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flEmail");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flPassword");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flPhoneNumber");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flUpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("flUserId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flUsername");

                    b.HasKey("Id");

                    b.ToTable("tbaccounts", "users");
                });

            modelBuilder.Entity("Prioritify.Data.Tables.TbAccountsOperations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("flOperationId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("OpType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flOpType");

                    b.Property<string>("OperationExecuter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flExecuter");

                    b.Property<string>("OperationModelJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flOpModelJson");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("flStatus");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flTimestamp");

                    b.HasKey("Id");

                    b.ToTable("tbaccountsops", "users");
                });

            modelBuilder.Entity("Prioritify.Data.Tables.TbRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("flRoleId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flCreatedAt");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("flRole");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flUpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("tbroles", "users");
                });

            modelBuilder.Entity("Prioritify.Data.Tables.TbUserRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("flId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("flAccountId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flCreatedAt");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("flRoleId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flUpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("flUserId");

                    b.HasKey("Id");

                    b.ToTable("tbuserroles", "users");
                });

            modelBuilder.Entity("Prioritify.Data.Tables.TbUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("flUserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flBirthDate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flCreatedAt");

                    b.Property<int>("Degree")
                        .HasColumnType("integer")
                        .HasColumnName("flDegree");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flFirstname");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("flGender");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flLastname");

                    b.Property<int>("StudyYear")
                        .HasColumnType("integer")
                        .HasColumnName("flStudyYear");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flUpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("tbusers", "users");
                });

            modelBuilder.Entity("Prioritify.Data.Tables.TbUsersOperations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("flOperationId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("OpType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flOpType");

                    b.Property<string>("OperationExecuter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flExecuter");

                    b.Property<string>("OperationModelJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flOpModelJson");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("flStatus");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flTimestamp");

                    b.HasKey("Id");

                    b.ToTable("tbusersops", "users");
                });
#pragma warning restore 612, 618
        }
    }
}
